-- ============================================================
-- Script: 001_create_tables.sql
-- Descripción: Crea las tablas base del Sistema Gestión
--              Biblioteca Personal
-- Base de datos: Oracle Autonomous Database 26ai
-- Ejecutar como: tu_usuario_oracle
-- ============================================================

-- Tabla de usuarios (HU-07, HU-08)
CREATE TABLE users (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            VARCHAR2(255)   NOT NULL,
    hashed_password  VARCHAR2(255)   NOT NULL,
    created_at       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- Tabla de libros (HU-01 a HU-04)
-- deleted_at implementa el soft-delete (HU-04)
CREATE TABLE books (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER          NOT NULL,
    title       VARCHAR2(500)   NOT NULL,
    author      VARCHAR2(255)   NOT NULL,
    isbn        VARCHAR2(20),
    year        NUMBER(4),
    genre       VARCHAR2(100),
    deleted_at  TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_books_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Índices para mejorar rendimiento de consultas frecuentes
CREATE INDEX idx_books_user_id    ON books(user_id);
CREATE INDEX idx_books_deleted_at ON books(deleted_at);

-- Comentarios de columnas (buena práctica Oracle)
COMMENT ON TABLE  users                  IS 'Usuarios registrados en la aplicación';
COMMENT ON COLUMN users.id               IS 'PK autoincremental';
COMMENT ON COLUMN users.email            IS 'Correo único, almacenado en minúsculas';
COMMENT ON COLUMN users.hashed_password  IS 'Hash bcrypt de la contraseña';

COMMENT ON TABLE  books                  IS 'Catálogo de libros por usuario';
COMMENT ON COLUMN books.user_id          IS 'FK al propietario del libro';
COMMENT ON COLUMN books.deleted_at       IS 'Soft delete: NULL = activo, valor = eliminado';

COMMIT;
