-- ============================================================
-- Script: 002_migrate_3nf.sql
-- Descripción: Migra el esquema a Tercera Forma Normal (3FN).
--              Nuevas tablas: AUTHORS, GENRES, PUBLISHERS, BOOK_AUTHORS
--              Modifica: BOOKS (elimina author/genre texto, agrega FKs)
-- Base de datos: Oracle Autonomous Database 26ai
-- IMPORTANTE: Ejecutar como BIBLIOTECA_PERSONAL
-- ============================================================

-- ------------------------------------------------------------
-- PASO 1: Crear tablas catálogo
-- ------------------------------------------------------------

CREATE TABLE genres (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_genres_name UNIQUE (name)
);

CREATE TABLE publishers (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(255) NOT NULL,
    CONSTRAINT uq_publishers_name UNIQUE (name)
);

CREATE TABLE authors (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(255) NOT NULL,
    CONSTRAINT uq_authors_name UNIQUE (name)
);

-- ------------------------------------------------------------
-- PASO 2: Migrar datos existentes de BOOKS hacia los catálogos
-- ------------------------------------------------------------

-- Migrar géneros únicos que ya existen en BOOKS
INSERT INTO genres (name)
    SELECT DISTINCT genre FROM books
    WHERE genre IS NOT NULL AND deleted_at IS NULL;

-- Migrar autores únicos que ya existen en BOOKS
INSERT INTO authors (name)
    SELECT DISTINCT author FROM books
    WHERE deleted_at IS NULL;

COMMIT;

-- ------------------------------------------------------------
-- PASO 3: Agregar nuevas columnas FK a BOOKS (nullable primero)
-- ------------------------------------------------------------

ALTER TABLE books ADD genre_id     NUMBER;
ALTER TABLE books ADD publisher_id NUMBER;

-- ------------------------------------------------------------
-- PASO 4: Poblar genre_id en filas existentes
-- ------------------------------------------------------------

UPDATE books b
SET b.genre_id = (
    SELECT g.id FROM genres g WHERE g.name = b.genre
)
WHERE b.genre IS NOT NULL AND b.deleted_at IS NULL;

COMMIT;

-- ------------------------------------------------------------
-- PASO 5: Agregar constraints FK a BOOKS
-- ------------------------------------------------------------

ALTER TABLE books ADD CONSTRAINT fk_books_genre
    FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE SET NULL;

ALTER TABLE books ADD CONSTRAINT fk_books_publisher
    FOREIGN KEY (publisher_id) REFERENCES publishers(id) ON DELETE SET NULL;

-- ------------------------------------------------------------
-- PASO 6: Crear tabla puente BOOK_AUTHORS (M:N)
-- ------------------------------------------------------------

CREATE TABLE book_authors (
    book_id   NUMBER NOT NULL,
    author_id NUMBER NOT NULL,
    CONSTRAINT pk_book_authors PRIMARY KEY (book_id, author_id),
    CONSTRAINT fk_ba_book   FOREIGN KEY (book_id)   REFERENCES books(id)   ON DELETE CASCADE,
    CONSTRAINT fk_ba_author FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- PASO 7: Poblar BOOK_AUTHORS con los autores existentes
-- ------------------------------------------------------------

INSERT INTO book_authors (book_id, author_id)
    SELECT b.id, a.id
    FROM books b
    JOIN authors a ON a.name = b.author
    WHERE b.deleted_at IS NULL;

COMMIT;

-- ------------------------------------------------------------
-- PASO 8: Eliminar columnas antiguas de BOOKS
-- ------------------------------------------------------------

ALTER TABLE books DROP COLUMN author;
ALTER TABLE books DROP COLUMN genre;

-- ------------------------------------------------------------
-- PASO 9: Índices de rendimiento
-- ------------------------------------------------------------

CREATE INDEX idx_books_genre_id     ON books(genre_id);
CREATE INDEX idx_books_publisher_id ON books(publisher_id);
CREATE INDEX idx_ba_author_id       ON book_authors(author_id);

-- ------------------------------------------------------------
-- PASO 10: Comentarios
-- ------------------------------------------------------------

COMMENT ON TABLE  genres              IS 'Catálogo de géneros literarios';
COMMENT ON TABLE  publishers          IS 'Catálogo de editoriales';
COMMENT ON TABLE  authors             IS 'Catálogo de autores únicos';
COMMENT ON TABLE  book_authors        IS 'Relación M:N entre libros y autores';
COMMENT ON COLUMN books.genre_id      IS 'FK al género del libro (nullable)';
COMMENT ON COLUMN books.publisher_id  IS 'FK a la editorial del libro (nullable)';

COMMIT;
