-- Recuperación y cambio seguro de contraseña. Ejecutar después de 001–005.
-- Aplicar primero en un esquema Oracle de pruebas, nunca automáticamente.
-- Oracle confirma DDL implícitamente: un ROLLBACK no deshace esta migración.

-- Versión incluida en los JWT. Incrementarla invalida todos los JWT anteriores
-- del usuario sin guardar cada token de acceso en la base de datos.
-- DEFAULT permite añadir NOT NULL incluso si USERS ya contiene filas.
ALTER TABLE users ADD (
    auth_version NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_users_auth_version CHECK (auth_version >= 0)
);

-- El enlace entrega un secreto aleatorio; aquí se guarda solo su SHA-256
-- hexadecimal. La aplicación fijará la expiración y marcará el consumo.
CREATE TABLE password_reset_tokens (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER NOT NULL,
    token_hash  CHAR(64) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_prt_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_prt_expiry CHECK (expires_at > created_at),
    CONSTRAINT chk_prt_consumed CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX idx_prt_user_status ON password_reset_tokens(user_id, consumed_at, expires_at);
CREATE INDEX idx_prt_expires_at ON password_reset_tokens(expires_at);

-- Historial de solicitudes, incluso para correos inexistentes, para aplicar
-- límites por cuenta y por origen sin revelar si una cuenta existe.
-- Los fingerprints serán HMAC-SHA-256 hexadecimales del correo normalizado y
-- de la IP de origen, calculados por la aplicación con un secreto de servidor.
-- Nunca almacenar correo, IP ni token en texto claro en esta tabla.
CREATE TABLE password_reset_requests (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_fingerprint  CHAR(64) NOT NULL,
    origin_fingerprint CHAR(64) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_prr_email_time ON password_reset_requests(email_fingerprint, created_at);
CREATE INDEX idx_prr_origin_time ON password_reset_requests(origin_fingerprint, created_at);
CREATE INDEX idx_prr_created_at ON password_reset_requests(created_at);

COMMENT ON COLUMN users.auth_version IS 'Versión de autenticación para invalidar JWT anteriores';
COMMENT ON TABLE password_reset_tokens IS 'Tokens de recuperación de un solo uso almacenados como hash';
COMMENT ON TABLE password_reset_requests IS 'Solicitudes de recuperación para límites de frecuencia';
COMMENT ON COLUMN password_reset_requests.email_fingerprint IS 'HMAC-SHA-256 hexadecimal del correo normalizado';
COMMENT ON COLUMN password_reset_requests.origin_fingerprint IS 'HMAC-SHA-256 hexadecimal del origen';
